name: pytest
on: push

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        python: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install autoscab
        run: pip install .[tests]
      - name: Run tests
        run: pytest tests
